### ISSUE TITLE
This repo is going to get HUGE!

### ISSUE THREAD

**Issue by agrez** [agrez/fedberry-kernel#7]
As the kernel.org source file is so big and I will have many kernel branches, this repo will eventually grow too large for people to comfortably work with. Github also has a size limit of 1GB and we are already at ~260mb!

Need to look at solutions for this issue:
- Probably the easiest solution is to have separate repos for each major kernel release (ie. kernel-4.3, kernel-4.4).
- Maybe pull out the kernel.org source file and make a nosrc.rpm? This would mean storing our upstream sources elsewhere and pulling them at build time (this would mean a change to my build scripts). Fedora seems to do this somehow.
- It would be nice if rpmbuild would pull in missing sources automatically at build time (like in Mageia). Why doesn't Fedora's rpmbuild do this?

**Comment by mrjoshuap** [comment]
For downloading sources, are you using spectool?

```
sudo dnf install rpmdevtools
```

I use it to download source files, used it for example to pull the fedberry-release.

```
$ spectool -g -R SPECS/fedberry-release.spec 
```

**Comment by agrez** [comment]
Ok, build scripts are updated to use spectool and a new kernel repo has been created. Closing this.
